# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('unique', models.CharField(max_length=40, unique=True)),
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=32)),
                ('auth', models.CharField(max_length=16)),
                ('pkey', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='创建时间')),
                ('port', models.IntegerField()),
                ('server_name', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=32)),
                ('ip_addr', models.GenericIPAddressField(unique=True)),
                ('auth', models.CharField(default='password', max_length=16)),
                ('pkey', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '宕机'), (3, '网络不可达'), (4, '下线')], default=1, verbose_name='状态')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '服务器信息',
                'verbose_name': '服务器信息',
            },
        ),
    ]
